force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_item__c/Invoice_Line_item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line item</label>
    <nameField>
        <displayFormat>ILI-{00000}</displayFormat>
        <label>Invoice Line item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_item__c/fields/InvoiceTO__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTO__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line items</relationshipLabel>
    <relationshipName>Invoice_Line_items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_item__c/fields/Transactionid__c.field-meta.xml
<CustomField>
    <fullName>Transactionid__c</fullName>
    <label>Transaction ID</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TriggerOnInvoiceLinehandler.cls
public class TriggerOnInvoiceLinehandler {
    
    public static void handlerOne(list<Invoice_Line_item__c> StartTrigger)
    {
        list<Invoice__c> updateinvoiceList = new list<Invoice__c>();
        map<id,Invoice__c> invoiceMap = new  map<id,Invoice__c>();
        set<id> invoiceIds =new set<id>();
        string transids ='';
        for(Invoice_Line_item__c invl:StartTrigger)
        {
         invoiceIds.add(invl.InvoiceTO__c);
        }
   		list<Invoice__c> invoiceList =[SELECT Id,Transaction_ID__c,(SELECT Id,InvoiceTO__c,Transactionid__c FROM Invoice_Line_items__r) FROM Invoice__c WHERE ID in:invoiceIds];
        for(Invoice__c inv:invoiceList )
        {
          for(Invoice_Line_item__c inl : inv.Invoice_Line_items__r)
          {
              transids = transids +' ' +inl.Transactionid__c;
              inv.Transaction_ID__c= transids;
              updateinvoiceList.add(inv);
              
          }
            invoiceMap.putall(updateinvoiceList);
        }
           
			update invoiceMap.values();
    }

}