force-app/main/default/objects/ExceptionBase__c/ExceptionBase__c.object-meta.xml
<CustomObject>
    <label>ExceptionBase</label>
    <nameField>
        <label>ExceptionBase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExceptionsBase</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExceptionBase__c/fields/lineNumber__c.field-meta.xml
<CustomField>
    <fullName>lineNumber__c</fullName>
    <label>lineNumber</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExceptionBase__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <label>MethodName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExceptionBase__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomExceptionClass.cls
//This class is used to store all exceptions in salesforce custom object
public class CustomExceptionClass {
 
    public static void storeExceptions(String className,string methodName,string errorMessage,Integer stackTrace,String lineNo)
    {
        //String line =String.valueOf(stackTrace);
        String trace = String.valueOf(stackTrace);
        ExceptionBase__c exceptionBase = new ExceptionBase__c();
        exceptionBase.ErrorMessage__c = errorMessage;
        exceptionBase.Name = className;
        exceptionBase.lineNumber__c = lineNo;
        exceptionBase.MethodName__c = methodName;
        exceptionBase.StackTrace__c = trace;
        Insert exceptionBase;
    }
}