force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Opp_Name__c.field-meta.xml
<CustomField>
    <fullName>Opp_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opp_Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Related_Document__c.field-meta.xml
<CustomField>
    <fullName>Related_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Folder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/recordTypes/Files.recordType-meta.xml
<RecordType>
    <fullName>Files</fullName>
    <active>true</active>
    <label>Files</label>
</RecordType>

force-app/main/default/objects/Document__c/recordTypes/Folder.recordType-meta.xml
<RecordType>
    <fullName>Folder</fullName>
    <active>true</active>
    <label>Folder</label>
</RecordType>

force-app/main/default/classes/DocsClass.cls
public with sharing class DocsClass {
    @AuraEnabled(cacheable=true)
    public static list<Document__c> getdocs(String oppid){
        try {
            id recotdtypeid=Schema.SObjectType.Document__c.getRecordTypeInfosByDeveloperName().get('Folder').getRecordTypeId();
        return [SELECT Id,Name FROM Document__c WHERE Opp_Name__c =:oppid AND RecordTypeId=:recotdtypeid ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Document__c> getFiles(string oppid,string folderid){
        try {
            id recotdtypeid=Schema.SObjectType.Document__c.getRecordTypeInfosByDeveloperName().get('Files').getRecordTypeId();
            return [SELECT Id,Name FROM Document__c WHERE Opp_Name__c =:oppid AND RecordTypeId=:recotdtypeid AND Related_Document__c=:folderid];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}