force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Related_Document__c.field-meta.xml
<CustomField>
    <fullName>Related_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Folder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/recordTypes/Files.recordType-meta.xml
<RecordType>
    <fullName>Files</fullName>
    <active>true</active>
    <label>Files</label>
</RecordType>

force-app/main/default/classes/DocumentsClass.cls
public class DocumentsClass {

    	public static list<Document__c> DocMethod()
        {
            list<Document__c> IdProofList = new list<Document__c>();
            list<Document__c> finProofList = new list<Document__c>();
            list<Document__c> propProofList = new list<Document__c>();
            id recordtypid= Schema.SObjectType.Document__c.getRecordTypeInfosByDeveloperName().get('Files').getRecordTypeId();
            List<Document__C> docList =[Select id,Name,Related_Document__c from  Document__c];
            for(Document__c Doc: docList)
            {
                if(Doc.Recordtypeid == recordtypid && Doc.Related_Document__c == 'ID PROOF')
                {
                    IdProofList.add(Doc);
                }
               else if(Doc.Recordtypeid == recordtypid && Doc.Related_Document__c == 'FINANCE PROOF')
               {
                   finProofList.add(Doc);
               }
                else if(Doc.Recordtypeid == recordtypid && Doc.Related_Document__c == 'PROPERTY DOCS')
                {
                    propProofList.add(Doc);
                }

            }
            	return IdProofList;
        }
}